// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iread_story.DataAccess.Data;

namespace iread_story.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211013094152_story_language_connection")]
    partial class story_language_connection
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            Active = false,
                            Code = "iv",
                            Name = "Invariant Language (Invariant Country)"
                        },
                        new
                        {
                            LanguageId = 2,
                            Active = false,
                            Code = "af",
                            Name = "Afrikaans"
                        },
                        new
                        {
                            LanguageId = 3,
                            Active = false,
                            Code = "agq",
                            Name = "Aghem"
                        },
                        new
                        {
                            LanguageId = 4,
                            Active = false,
                            Code = "ak",
                            Name = "Akan"
                        },
                        new
                        {
                            LanguageId = 5,
                            Active = false,
                            Code = "am",
                            Name = "Amharic"
                        },
                        new
                        {
                            LanguageId = 6,
                            Active = false,
                            Code = "ar",
                            Name = "Arabic"
                        },
                        new
                        {
                            LanguageId = 7,
                            Active = false,
                            Code = "as",
                            Name = "Assamese"
                        },
                        new
                        {
                            LanguageId = 8,
                            Active = false,
                            Code = "asa",
                            Name = "Asu"
                        },
                        new
                        {
                            LanguageId = 9,
                            Active = false,
                            Code = "ast",
                            Name = "Asturian"
                        },
                        new
                        {
                            LanguageId = 10,
                            Active = false,
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = 11,
                            Active = false,
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = 12,
                            Active = false,
                            Code = "az",
                            Name = "Azerbaijani"
                        },
                        new
                        {
                            LanguageId = 13,
                            Active = false,
                            Code = "bas",
                            Name = "Basaa"
                        },
                        new
                        {
                            LanguageId = 14,
                            Active = false,
                            Code = "be",
                            Name = "Belarusian"
                        },
                        new
                        {
                            LanguageId = 15,
                            Active = false,
                            Code = "bem",
                            Name = "Bemba"
                        },
                        new
                        {
                            LanguageId = 16,
                            Active = false,
                            Code = "bez",
                            Name = "Bena"
                        },
                        new
                        {
                            LanguageId = 17,
                            Active = false,
                            Code = "bg",
                            Name = "Bulgarian"
                        },
                        new
                        {
                            LanguageId = 18,
                            Active = false,
                            Code = "bm",
                            Name = "Bambara"
                        },
                        new
                        {
                            LanguageId = 19,
                            Active = false,
                            Code = "bn",
                            Name = "Bangla"
                        },
                        new
                        {
                            LanguageId = 20,
                            Active = false,
                            Code = "bo",
                            Name = "Tibetan"
                        },
                        new
                        {
                            LanguageId = 21,
                            Active = false,
                            Code = "br",
                            Name = "Breton"
                        },
                        new
                        {
                            LanguageId = 22,
                            Active = false,
                            Code = "brx",
                            Name = "Bodo"
                        },
                        new
                        {
                            LanguageId = 23,
                            Active = false,
                            Code = "bs",
                            Name = "Bosnian"
                        },
                        new
                        {
                            LanguageId = 24,
                            Active = false,
                            Code = "bs",
                            Name = "Bosnian"
                        },
                        new
                        {
                            LanguageId = 25,
                            Active = false,
                            Code = "bs",
                            Name = "Bosnian"
                        },
                        new
                        {
                            LanguageId = 26,
                            Active = false,
                            Code = "ca",
                            Name = "Catalan"
                        },
                        new
                        {
                            LanguageId = 27,
                            Active = false,
                            Code = "ccp",
                            Name = "Chakma"
                        },
                        new
                        {
                            LanguageId = 28,
                            Active = false,
                            Code = "ce",
                            Name = "Chechen"
                        },
                        new
                        {
                            LanguageId = 29,
                            Active = false,
                            Code = "ceb",
                            Name = "Cebuano"
                        },
                        new
                        {
                            LanguageId = 30,
                            Active = false,
                            Code = "cgg",
                            Name = "Chiga"
                        },
                        new
                        {
                            LanguageId = 31,
                            Active = false,
                            Code = "chr",
                            Name = "Cherokee"
                        },
                        new
                        {
                            LanguageId = 32,
                            Active = false,
                            Code = "ckb",
                            Name = "Central Kurdish"
                        },
                        new
                        {
                            LanguageId = 33,
                            Active = false,
                            Code = "cs",
                            Name = "Czech"
                        },
                        new
                        {
                            LanguageId = 34,
                            Active = false,
                            Code = "cy",
                            Name = "Welsh"
                        },
                        new
                        {
                            LanguageId = 35,
                            Active = false,
                            Code = "da",
                            Name = "Danish"
                        },
                        new
                        {
                            LanguageId = 36,
                            Active = false,
                            Code = "dav",
                            Name = "Taita"
                        },
                        new
                        {
                            LanguageId = 37,
                            Active = false,
                            Code = "de",
                            Name = "German"
                        },
                        new
                        {
                            LanguageId = 38,
                            Active = false,
                            Code = "dje",
                            Name = "Zarma"
                        },
                        new
                        {
                            LanguageId = 39,
                            Active = false,
                            Code = "dsb",
                            Name = "Lower Sorbian"
                        },
                        new
                        {
                            LanguageId = 40,
                            Active = false,
                            Code = "dua",
                            Name = "Duala"
                        },
                        new
                        {
                            LanguageId = 41,
                            Active = false,
                            Code = "dyo",
                            Name = "Jola-Fonyi"
                        },
                        new
                        {
                            LanguageId = 42,
                            Active = false,
                            Code = "dz",
                            Name = "Dzongkha"
                        },
                        new
                        {
                            LanguageId = 43,
                            Active = false,
                            Code = "ebu",
                            Name = "Embu"
                        },
                        new
                        {
                            LanguageId = 44,
                            Active = false,
                            Code = "ee",
                            Name = "Ewe"
                        },
                        new
                        {
                            LanguageId = 45,
                            Active = false,
                            Code = "el",
                            Name = "Greek"
                        },
                        new
                        {
                            LanguageId = 46,
                            Active = false,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            LanguageId = 47,
                            Active = false,
                            Code = "eo",
                            Name = "Esperanto"
                        },
                        new
                        {
                            LanguageId = 48,
                            Active = false,
                            Code = "es",
                            Name = "Spanish"
                        },
                        new
                        {
                            LanguageId = 49,
                            Active = false,
                            Code = "et",
                            Name = "Estonian"
                        },
                        new
                        {
                            LanguageId = 50,
                            Active = false,
                            Code = "eu",
                            Name = "Basque"
                        },
                        new
                        {
                            LanguageId = 51,
                            Active = false,
                            Code = "ewo",
                            Name = "Ewondo"
                        },
                        new
                        {
                            LanguageId = 52,
                            Active = false,
                            Code = "fa",
                            Name = "Persian"
                        },
                        new
                        {
                            LanguageId = 53,
                            Active = false,
                            Code = "ff",
                            Name = "Fulah"
                        },
                        new
                        {
                            LanguageId = 54,
                            Active = false,
                            Code = "ff",
                            Name = "Fulah"
                        },
                        new
                        {
                            LanguageId = 55,
                            Active = false,
                            Code = "fi",
                            Name = "Finnish"
                        },
                        new
                        {
                            LanguageId = 56,
                            Active = false,
                            Code = "fil",
                            Name = "Filipino"
                        },
                        new
                        {
                            LanguageId = 57,
                            Active = false,
                            Code = "fo",
                            Name = "Faroese"
                        },
                        new
                        {
                            LanguageId = 58,
                            Active = false,
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            LanguageId = 59,
                            Active = false,
                            Code = "fur",
                            Name = "Friulian"
                        },
                        new
                        {
                            LanguageId = 60,
                            Active = false,
                            Code = "fy",
                            Name = "Western Frisian"
                        },
                        new
                        {
                            LanguageId = 61,
                            Active = false,
                            Code = "ga",
                            Name = "Irish"
                        },
                        new
                        {
                            LanguageId = 62,
                            Active = false,
                            Code = "gd",
                            Name = "Scottish Gaelic"
                        },
                        new
                        {
                            LanguageId = 63,
                            Active = false,
                            Code = "gl",
                            Name = "Galician"
                        },
                        new
                        {
                            LanguageId = 64,
                            Active = false,
                            Code = "gsw",
                            Name = "Swiss German"
                        },
                        new
                        {
                            LanguageId = 65,
                            Active = false,
                            Code = "gu",
                            Name = "Gujarati"
                        },
                        new
                        {
                            LanguageId = 66,
                            Active = false,
                            Code = "guz",
                            Name = "Gusii"
                        },
                        new
                        {
                            LanguageId = 67,
                            Active = false,
                            Code = "gv",
                            Name = "Manx"
                        },
                        new
                        {
                            LanguageId = 68,
                            Active = false,
                            Code = "ha",
                            Name = "Hausa"
                        },
                        new
                        {
                            LanguageId = 69,
                            Active = false,
                            Code = "haw",
                            Name = "Hawaiian"
                        },
                        new
                        {
                            LanguageId = 70,
                            Active = false,
                            Code = "he",
                            Name = "Hebrew"
                        },
                        new
                        {
                            LanguageId = 71,
                            Active = false,
                            Code = "hi",
                            Name = "Hindi"
                        },
                        new
                        {
                            LanguageId = 72,
                            Active = false,
                            Code = "hr",
                            Name = "Croatian"
                        },
                        new
                        {
                            LanguageId = 73,
                            Active = false,
                            Code = "hsb",
                            Name = "Upper Sorbian"
                        },
                        new
                        {
                            LanguageId = 74,
                            Active = false,
                            Code = "hu",
                            Name = "Hungarian"
                        },
                        new
                        {
                            LanguageId = 75,
                            Active = false,
                            Code = "hy",
                            Name = "Armenian"
                        },
                        new
                        {
                            LanguageId = 76,
                            Active = false,
                            Code = "ia",
                            Name = "Interlingua"
                        },
                        new
                        {
                            LanguageId = 77,
                            Active = false,
                            Code = "id",
                            Name = "Indonesian"
                        },
                        new
                        {
                            LanguageId = 78,
                            Active = false,
                            Code = "ig",
                            Name = "Igbo"
                        },
                        new
                        {
                            LanguageId = 79,
                            Active = false,
                            Code = "ii",
                            Name = "Sichuan Yi"
                        },
                        new
                        {
                            LanguageId = 80,
                            Active = false,
                            Code = "is",
                            Name = "Icelandic"
                        },
                        new
                        {
                            LanguageId = 81,
                            Active = false,
                            Code = "it",
                            Name = "Italian"
                        },
                        new
                        {
                            LanguageId = 82,
                            Active = false,
                            Code = "ja",
                            Name = "Japanese"
                        },
                        new
                        {
                            LanguageId = 83,
                            Active = false,
                            Code = "jgo",
                            Name = "Ngomba"
                        },
                        new
                        {
                            LanguageId = 84,
                            Active = false,
                            Code = "jmc",
                            Name = "Machame"
                        },
                        new
                        {
                            LanguageId = 85,
                            Active = false,
                            Code = "jv",
                            Name = "Javanese"
                        },
                        new
                        {
                            LanguageId = 86,
                            Active = false,
                            Code = "ka",
                            Name = "Georgian"
                        },
                        new
                        {
                            LanguageId = 87,
                            Active = false,
                            Code = "kab",
                            Name = "Kabyle"
                        },
                        new
                        {
                            LanguageId = 88,
                            Active = false,
                            Code = "kam",
                            Name = "Kamba"
                        },
                        new
                        {
                            LanguageId = 89,
                            Active = false,
                            Code = "kde",
                            Name = "Makonde"
                        },
                        new
                        {
                            LanguageId = 90,
                            Active = false,
                            Code = "kea",
                            Name = "Kabuverdianu"
                        },
                        new
                        {
                            LanguageId = 91,
                            Active = false,
                            Code = "khq",
                            Name = "Koyra Chiini"
                        },
                        new
                        {
                            LanguageId = 92,
                            Active = false,
                            Code = "ki",
                            Name = "Kikuyu"
                        },
                        new
                        {
                            LanguageId = 93,
                            Active = false,
                            Code = "kk",
                            Name = "Kazakh"
                        },
                        new
                        {
                            LanguageId = 94,
                            Active = false,
                            Code = "kkj",
                            Name = "Kako"
                        },
                        new
                        {
                            LanguageId = 95,
                            Active = false,
                            Code = "kl",
                            Name = "Kalaallisut"
                        },
                        new
                        {
                            LanguageId = 96,
                            Active = false,
                            Code = "kln",
                            Name = "Kalenjin"
                        },
                        new
                        {
                            LanguageId = 97,
                            Active = false,
                            Code = "km",
                            Name = "Khmer"
                        },
                        new
                        {
                            LanguageId = 98,
                            Active = false,
                            Code = "kn",
                            Name = "Kannada"
                        },
                        new
                        {
                            LanguageId = 99,
                            Active = false,
                            Code = "ko",
                            Name = "Korean"
                        },
                        new
                        {
                            LanguageId = 100,
                            Active = false,
                            Code = "kok",
                            Name = "Konkani"
                        },
                        new
                        {
                            LanguageId = 101,
                            Active = false,
                            Code = "ks",
                            Name = "Kashmiri"
                        },
                        new
                        {
                            LanguageId = 102,
                            Active = false,
                            Code = "ksb",
                            Name = "Shambala"
                        },
                        new
                        {
                            LanguageId = 103,
                            Active = false,
                            Code = "ksf",
                            Name = "Bafia"
                        },
                        new
                        {
                            LanguageId = 104,
                            Active = false,
                            Code = "ksh",
                            Name = "Colognian"
                        },
                        new
                        {
                            LanguageId = 105,
                            Active = false,
                            Code = "ku",
                            Name = "Kurdish"
                        },
                        new
                        {
                            LanguageId = 106,
                            Active = false,
                            Code = "kw",
                            Name = "Cornish"
                        },
                        new
                        {
                            LanguageId = 107,
                            Active = false,
                            Code = "ky",
                            Name = "Kyrgyz"
                        },
                        new
                        {
                            LanguageId = 108,
                            Active = false,
                            Code = "lag",
                            Name = "Langi"
                        },
                        new
                        {
                            LanguageId = 109,
                            Active = false,
                            Code = "lb",
                            Name = "Luxembourgish"
                        },
                        new
                        {
                            LanguageId = 110,
                            Active = false,
                            Code = "lg",
                            Name = "Ganda"
                        },
                        new
                        {
                            LanguageId = 111,
                            Active = false,
                            Code = "lkt",
                            Name = "Lakota"
                        },
                        new
                        {
                            LanguageId = 112,
                            Active = false,
                            Code = "ln",
                            Name = "Lingala"
                        },
                        new
                        {
                            LanguageId = 113,
                            Active = false,
                            Code = "lo",
                            Name = "Lao"
                        },
                        new
                        {
                            LanguageId = 114,
                            Active = false,
                            Code = "lrc",
                            Name = "Northern Luri"
                        },
                        new
                        {
                            LanguageId = 115,
                            Active = false,
                            Code = "lt",
                            Name = "Lithuanian"
                        },
                        new
                        {
                            LanguageId = 116,
                            Active = false,
                            Code = "lu",
                            Name = "Luba-Katanga"
                        },
                        new
                        {
                            LanguageId = 117,
                            Active = false,
                            Code = "luo",
                            Name = "Luo"
                        },
                        new
                        {
                            LanguageId = 118,
                            Active = false,
                            Code = "luy",
                            Name = "Luyia"
                        },
                        new
                        {
                            LanguageId = 119,
                            Active = false,
                            Code = "lv",
                            Name = "Latvian"
                        },
                        new
                        {
                            LanguageId = 120,
                            Active = false,
                            Code = "mas",
                            Name = "Masai"
                        },
                        new
                        {
                            LanguageId = 121,
                            Active = false,
                            Code = "mer",
                            Name = "Meru"
                        },
                        new
                        {
                            LanguageId = 122,
                            Active = false,
                            Code = "mfe",
                            Name = "Morisyen"
                        },
                        new
                        {
                            LanguageId = 123,
                            Active = false,
                            Code = "mg",
                            Name = "Malagasy"
                        },
                        new
                        {
                            LanguageId = 124,
                            Active = false,
                            Code = "mgh",
                            Name = "Makhuwa-Meetto"
                        },
                        new
                        {
                            LanguageId = 125,
                            Active = false,
                            Code = "mgo",
                            Name = "Metaʼ"
                        },
                        new
                        {
                            LanguageId = 126,
                            Active = false,
                            Code = "mi",
                            Name = "Maori"
                        },
                        new
                        {
                            LanguageId = 127,
                            Active = false,
                            Code = "mk",
                            Name = "Macedonian"
                        },
                        new
                        {
                            LanguageId = 128,
                            Active = false,
                            Code = "ml",
                            Name = "Malayalam"
                        },
                        new
                        {
                            LanguageId = 129,
                            Active = false,
                            Code = "mn",
                            Name = "Mongolian"
                        },
                        new
                        {
                            LanguageId = 130,
                            Active = false,
                            Code = "mr",
                            Name = "Marathi"
                        },
                        new
                        {
                            LanguageId = 131,
                            Active = false,
                            Code = "ms",
                            Name = "Malay"
                        },
                        new
                        {
                            LanguageId = 132,
                            Active = false,
                            Code = "mt",
                            Name = "Maltese"
                        },
                        new
                        {
                            LanguageId = 133,
                            Active = false,
                            Code = "mua",
                            Name = "Mundang"
                        },
                        new
                        {
                            LanguageId = 134,
                            Active = false,
                            Code = "my",
                            Name = "Burmese"
                        },
                        new
                        {
                            LanguageId = 135,
                            Active = false,
                            Code = "mzn",
                            Name = "Mazanderani"
                        },
                        new
                        {
                            LanguageId = 136,
                            Active = false,
                            Code = "naq",
                            Name = "Nama"
                        },
                        new
                        {
                            LanguageId = 137,
                            Active = false,
                            Code = "nb",
                            Name = "Norwegian Bokmål"
                        },
                        new
                        {
                            LanguageId = 138,
                            Active = false,
                            Code = "nd",
                            Name = "North Ndebele"
                        },
                        new
                        {
                            LanguageId = 139,
                            Active = false,
                            Code = "nds",
                            Name = "Low German"
                        },
                        new
                        {
                            LanguageId = 140,
                            Active = false,
                            Code = "ne",
                            Name = "Nepali"
                        },
                        new
                        {
                            LanguageId = 141,
                            Active = false,
                            Code = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            LanguageId = 142,
                            Active = false,
                            Code = "nmg",
                            Name = "Kwasio"
                        },
                        new
                        {
                            LanguageId = 143,
                            Active = false,
                            Code = "nn",
                            Name = "Norwegian Nynorsk"
                        },
                        new
                        {
                            LanguageId = 144,
                            Active = false,
                            Code = "nnh",
                            Name = "Ngiemboon"
                        },
                        new
                        {
                            LanguageId = 145,
                            Active = false,
                            Code = "nus",
                            Name = "Nuer"
                        },
                        new
                        {
                            LanguageId = 146,
                            Active = false,
                            Code = "nyn",
                            Name = "Nyankole"
                        },
                        new
                        {
                            LanguageId = 147,
                            Active = false,
                            Code = "om",
                            Name = "Oromo"
                        },
                        new
                        {
                            LanguageId = 148,
                            Active = false,
                            Code = "or",
                            Name = "Odia"
                        },
                        new
                        {
                            LanguageId = 149,
                            Active = false,
                            Code = "os",
                            Name = "Ossetic"
                        },
                        new
                        {
                            LanguageId = 150,
                            Active = false,
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            LanguageId = 151,
                            Active = false,
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            LanguageId = 152,
                            Active = false,
                            Code = "pa",
                            Name = "Punjabi"
                        },
                        new
                        {
                            LanguageId = 153,
                            Active = false,
                            Code = "pl",
                            Name = "Polish"
                        },
                        new
                        {
                            LanguageId = 154,
                            Active = false,
                            Code = "ps",
                            Name = "Pashto"
                        },
                        new
                        {
                            LanguageId = 155,
                            Active = false,
                            Code = "pt",
                            Name = "Portuguese"
                        },
                        new
                        {
                            LanguageId = 156,
                            Active = false,
                            Code = "qu",
                            Name = "Quechua"
                        },
                        new
                        {
                            LanguageId = 157,
                            Active = false,
                            Code = "rm",
                            Name = "Romansh"
                        },
                        new
                        {
                            LanguageId = 158,
                            Active = false,
                            Code = "rn",
                            Name = "Rundi"
                        },
                        new
                        {
                            LanguageId = 159,
                            Active = false,
                            Code = "ro",
                            Name = "Romanian"
                        },
                        new
                        {
                            LanguageId = 160,
                            Active = false,
                            Code = "rof",
                            Name = "Rombo"
                        },
                        new
                        {
                            LanguageId = 161,
                            Active = false,
                            Code = "ru",
                            Name = "Russian"
                        },
                        new
                        {
                            LanguageId = 162,
                            Active = false,
                            Code = "rw",
                            Name = "Kinyarwanda"
                        },
                        new
                        {
                            LanguageId = 163,
                            Active = false,
                            Code = "rwk",
                            Name = "Rwa"
                        },
                        new
                        {
                            LanguageId = 164,
                            Active = false,
                            Code = "sah",
                            Name = "Sakha"
                        },
                        new
                        {
                            LanguageId = 165,
                            Active = false,
                            Code = "saq",
                            Name = "Samburu"
                        },
                        new
                        {
                            LanguageId = 166,
                            Active = false,
                            Code = "sbp",
                            Name = "Sangu"
                        },
                        new
                        {
                            LanguageId = 167,
                            Active = false,
                            Code = "sd",
                            Name = "Sindhi"
                        },
                        new
                        {
                            LanguageId = 168,
                            Active = false,
                            Code = "se",
                            Name = "Northern Sami"
                        },
                        new
                        {
                            LanguageId = 169,
                            Active = false,
                            Code = "seh",
                            Name = "Sena"
                        },
                        new
                        {
                            LanguageId = 170,
                            Active = false,
                            Code = "ses",
                            Name = "Koyraboro Senni"
                        },
                        new
                        {
                            LanguageId = 171,
                            Active = false,
                            Code = "sg",
                            Name = "Sango"
                        },
                        new
                        {
                            LanguageId = 172,
                            Active = false,
                            Code = "shi",
                            Name = "Tachelhit"
                        },
                        new
                        {
                            LanguageId = 173,
                            Active = false,
                            Code = "shi",
                            Name = "Tachelhit"
                        },
                        new
                        {
                            LanguageId = 174,
                            Active = false,
                            Code = "shi",
                            Name = "Tachelhit"
                        },
                        new
                        {
                            LanguageId = 175,
                            Active = false,
                            Code = "si",
                            Name = "Sinhala"
                        },
                        new
                        {
                            LanguageId = 176,
                            Active = false,
                            Code = "sk",
                            Name = "Slovak"
                        },
                        new
                        {
                            LanguageId = 177,
                            Active = false,
                            Code = "sl",
                            Name = "Slovenian"
                        },
                        new
                        {
                            LanguageId = 178,
                            Active = false,
                            Code = "smn",
                            Name = "Inari Sami"
                        },
                        new
                        {
                            LanguageId = 179,
                            Active = false,
                            Code = "sn",
                            Name = "Shona"
                        },
                        new
                        {
                            LanguageId = 180,
                            Active = false,
                            Code = "so",
                            Name = "Somali"
                        },
                        new
                        {
                            LanguageId = 181,
                            Active = false,
                            Code = "sq",
                            Name = "Albanian"
                        },
                        new
                        {
                            LanguageId = 182,
                            Active = false,
                            Code = "sr",
                            Name = "Serbian"
                        },
                        new
                        {
                            LanguageId = 183,
                            Active = false,
                            Code = "sr",
                            Name = "Serbian"
                        },
                        new
                        {
                            LanguageId = 184,
                            Active = false,
                            Code = "sr",
                            Name = "Serbian"
                        },
                        new
                        {
                            LanguageId = 185,
                            Active = false,
                            Code = "sv",
                            Name = "Swedish"
                        },
                        new
                        {
                            LanguageId = 186,
                            Active = false,
                            Code = "sw",
                            Name = "Swahili"
                        },
                        new
                        {
                            LanguageId = 187,
                            Active = false,
                            Code = "ta",
                            Name = "Tamil"
                        },
                        new
                        {
                            LanguageId = 188,
                            Active = false,
                            Code = "te",
                            Name = "Telugu"
                        },
                        new
                        {
                            LanguageId = 189,
                            Active = false,
                            Code = "teo",
                            Name = "Teso"
                        },
                        new
                        {
                            LanguageId = 190,
                            Active = false,
                            Code = "tg",
                            Name = "Tajik"
                        },
                        new
                        {
                            LanguageId = 191,
                            Active = false,
                            Code = "th",
                            Name = "Thai"
                        },
                        new
                        {
                            LanguageId = 192,
                            Active = false,
                            Code = "ti",
                            Name = "Tigrinya"
                        },
                        new
                        {
                            LanguageId = 193,
                            Active = false,
                            Code = "tk",
                            Name = "Turkmen"
                        },
                        new
                        {
                            LanguageId = 194,
                            Active = false,
                            Code = "to",
                            Name = "Tongan"
                        },
                        new
                        {
                            LanguageId = 195,
                            Active = false,
                            Code = "tr",
                            Name = "Turkish"
                        },
                        new
                        {
                            LanguageId = 196,
                            Active = false,
                            Code = "tt",
                            Name = "Tatar"
                        },
                        new
                        {
                            LanguageId = 197,
                            Active = false,
                            Code = "twq",
                            Name = "Tasawaq"
                        },
                        new
                        {
                            LanguageId = 198,
                            Active = false,
                            Code = "tzm",
                            Name = "Central Atlas Tamazight"
                        },
                        new
                        {
                            LanguageId = 199,
                            Active = false,
                            Code = "ug",
                            Name = "Uyghur"
                        },
                        new
                        {
                            LanguageId = 200,
                            Active = false,
                            Code = "uk",
                            Name = "Ukrainian"
                        },
                        new
                        {
                            LanguageId = 201,
                            Active = false,
                            Code = "ur",
                            Name = "Urdu"
                        },
                        new
                        {
                            LanguageId = 202,
                            Active = false,
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            LanguageId = 203,
                            Active = false,
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            LanguageId = 204,
                            Active = false,
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            LanguageId = 205,
                            Active = false,
                            Code = "uz",
                            Name = "Uzbek"
                        },
                        new
                        {
                            LanguageId = 206,
                            Active = false,
                            Code = "vai",
                            Name = "Vai"
                        },
                        new
                        {
                            LanguageId = 207,
                            Active = false,
                            Code = "vai",
                            Name = "Vai"
                        },
                        new
                        {
                            LanguageId = 208,
                            Active = false,
                            Code = "vai",
                            Name = "Vai"
                        },
                        new
                        {
                            LanguageId = 209,
                            Active = false,
                            Code = "vi",
                            Name = "Vietnamese"
                        },
                        new
                        {
                            LanguageId = 210,
                            Active = false,
                            Code = "vun",
                            Name = "Vunjo"
                        },
                        new
                        {
                            LanguageId = 211,
                            Active = false,
                            Code = "wae",
                            Name = "Walser"
                        },
                        new
                        {
                            LanguageId = 212,
                            Active = false,
                            Code = "wo",
                            Name = "Wolof"
                        },
                        new
                        {
                            LanguageId = 213,
                            Active = false,
                            Code = "xh",
                            Name = "Xhosa"
                        },
                        new
                        {
                            LanguageId = 214,
                            Active = false,
                            Code = "xog",
                            Name = "Soga"
                        },
                        new
                        {
                            LanguageId = 215,
                            Active = false,
                            Code = "yav",
                            Name = "Yangben"
                        },
                        new
                        {
                            LanguageId = 216,
                            Active = false,
                            Code = "yi",
                            Name = "Yiddish"
                        },
                        new
                        {
                            LanguageId = 217,
                            Active = false,
                            Code = "yo",
                            Name = "Yoruba"
                        },
                        new
                        {
                            LanguageId = 218,
                            Active = false,
                            Code = "yue",
                            Name = "Cantonese"
                        },
                        new
                        {
                            LanguageId = 219,
                            Active = false,
                            Code = "yue",
                            Name = "Cantonese"
                        },
                        new
                        {
                            LanguageId = 220,
                            Active = false,
                            Code = "yue",
                            Name = "Cantonese"
                        },
                        new
                        {
                            LanguageId = 221,
                            Active = false,
                            Code = "zgh",
                            Name = "Standard Moroccan Tamazight"
                        },
                        new
                        {
                            LanguageId = 222,
                            Active = false,
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            LanguageId = 223,
                            Active = false,
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            LanguageId = 224,
                            Active = false,
                            Code = "zh",
                            Name = "Chinese"
                        },
                        new
                        {
                            LanguageId = 225,
                            Active = false,
                            Code = "zu",
                            Name = "Zulu"
                        });
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Page", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ImageId")
                        .HasColumnType("int");

                    b.Property<int>("No")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Words")
                        .HasColumnType("text");

                    b.HasKey("PageId");

                    b.HasIndex("StoryId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AudioId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("CoverId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("ManagerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime");

                    b.Property<int>("StoryLevel")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Writer")
                        .HasColumnType("text");

                    b.HasKey("StoryId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Page", b =>
                {
                    b.HasOne("iread_story.DataAccess.Data.Entity.Story", "Story")
                        .WithMany("Pages")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Story", b =>
                {
                    b.HasOne("iread_story.DataAccess.Data.Entity.Language", "Language")
                        .WithMany("Stories")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Language", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("iread_story.DataAccess.Data.Entity.Story", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
